name: Deploy PROD

on:
  push:
    branches:
      - main

jobs:
  PROD:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: crazyllama.app
          username: developer
          port: 22
          password: dev3H19J21
          script: |
            cd /opt/crazy-english-general-prod/crazy-english-tgbot
            git switch main
            git pull
            cd ../
            docker-compose up -d --build bot
